[project]
name = "future-ai-engineer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "isaacabderman-creator", email = "hei.isaac.2@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
future-ai-engineer = "future_ai_engineer:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "boto3>=1.43.70",
]
